### ISSUE TITLE
Dont know how to fix vulnerabilities with bun

### ISSUE THREAD

**Issue by wweitzel** [wweitzel/top90-frontend#115]
There is no `bun audit` and `bun audit fix` like there is when using npm.

How do we fix vulnerabilities when using bun as package manager? If there is no way to deal with this, we need to switch back to npm.

**Comment by astone123** [comment]
Looks like there isn't support for an option like that according to https://github.com/oven-sh/bun/issues/5359. There's a workaround to write the bun lockfile to a yarn lockfile and then use `yarn audit` to check the deps, but it's probably easier just to go back to using npm.

**Comment by wweitzel** [comment]
We have switched back to npm https://github.com/wweitzel/top90-frontend/pull/119
