### ISSUE TITLE
Switch to Vite

### ISSUE THREAD

**Issue by wweitzel** [wweitzel/top90-frontend#28]
Project was originally made with create-react-app. We want to switch over to Vite.

Here is a potential guide https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

**Comment by GIT-Gizmo** [comment]
Hi, I can help with this. Feel free to assign the issue to me

**Comment by wweitzel** [comment]
Sweet, all yours.

**Comment by wweitzel** [comment]
Closing now that this is complete. Thanks @GIT-Gizmo

**Comment by GIT-Gizmo** [comment]
> Closing now that this is complete. Thanks @GIT-Gizmo

You're welcome 👍
