### ISSUE TITLE
Fix app double rendering on initial load

### ISSUE THREAD

**Issue by wweitzel** [wweitzel/top90-frontend#8]
**What is going on**
The app seems to be double rendering on initial page load. This is resulting in two api requests to the backend.

**Work Items**
Refactor App.js so that it only renders once on initial page load

**Comment by TimothyLoo** [comment]
Hi there! I found this open-source project on https://goodfirstissues.com/ and wanted to try my hand at contributing!
In regard to this issue, I think React will render multiple times, but I have implemented the use of React.memo so the API call only happens once on the initial page load. #9
Please let me know if there's anything else I can help with. I would also be open to any feedback regarding best practices for contributing to open-source projects.
Thank you!

**Comment by wweitzel** [comment]
Cool thanks! I responded in the PR https://github.com/wweitzel/top90-frontend/pull/9

**Comment by wweitzel** [comment]
I'm going to close this issue since its technically fixed now. But as mentioned in #9, we still need the new goal page.
