### ISSUE TITLE
Cache league and team icons to avoid rate limiting

### ISSUE THREAD

**Issue by astone123** [wweitzel/top90-frontend#94]
Sometimes we hit a rate limit when loading team and league logos from `media.api-sports.io` which results in the screenshot below. These images will rarely ever change - if the browser loads them one time, we should cache them indefinitely to avoid hitting that API on every page load.

<img width="335" alt="Screenshot 2023-12-16 at 11 42 53 AM" src="https://github.com/wweitzel/top90-frontend/assets/14275198/d2b1a15d-e072-4347-b89a-a11b601c3dbc">

**Comment by wweitzel** [comment]
Maybe cache yearly? Team logo would only change with a new season. It is still going to be rare that it changes but maybe best to be ready if it does.

Also are there limits on amount of data a web app can store? Theres a lot of teams and the full resolution logo is larger than what shows up on the page (so the data would be more than you might think). Just thoughts.

**Comment by wweitzel** [comment]
I randomly selected 3 logos and the max size was 14KB. We have 586 teams so 14 * 586 = 8204KB so 8.2MB.

**Comment by astone123** [comment]
it looks like these are actually getting cached right now. going to close this in favor of a more comprehensive solution for querying external APIs
